### ISSUE TITLE
Initial Code Release Testing

### ISSUE THREAD

**Issue by alleghenycreative** [OpenRepeater/documents#11]
@OpenRepeater/developers 
Hello Gang. It has been about 2 weeks since I released the initial test image of OpenRepeater for the Raspberry Pi. I just wanted to follow up with everyone to see what their experiences are with testing or if there are any initial concerns. 

We are still working on setting up the GitHub repositories and @mathewpeterson has been a big help in providing some direction and getting it going. I am also working on a build scripts to setup new systems. It's not quite there yet and will eventually have it's own repository under the OpenRepeater organization on GitHub. Right now the best way to get started with OpenRepeater is with the image that was sent out in the email 2 weeks ago as it is precompiled with all the dependancies. Thanks.

**Comment by f5nlg** [comment]
hello all , the ssh password doesn't work OpenRepeater  ... and to much complicated meaning A on French keyboard is Q why don't yu put toor like password ... failtoban doesn't must not start at first boot but have to select from control pannel ( my point of view ) , i search to login in SSH for now ...

**Comment by alleghenycreative** [comment]
Please see this forum thread: 
http://openrepeater.com/forums/topic/default-ssh-password-not-working

I will take a look at your other post when I get a chance. Thanks. 


Aaron Crawford
Allegheny Creative, LLC
P.O. Box 681
Falling Waters, WV 25419-0681
304-274-1800 phone
www.AlleghenyCreative.com 

    
NOTICE: This communication is confidential and intended only for the person or entity to which it is addressed and may be legally privileged. If you are not the intended recipient, you are hereby notified that you have received this message in error and that any review, dissemination, distribution or copying of this message including any attachments is strictly prohibited. Please notify the sender by reply mail, and delete this communication from your system. Failure to follow this process may be unlawful. Opinions, Declarations, conclusions or any other information contained or attached to this message that do not relate to the official business of Allegheny Creative, LLC shall be understood as neither given nor endorsed by it.

**Comment by f5nlg** [comment]
hi,

debian is a good password ... for setup the system , no need to more 
complicate it i think the system must be configurate ,and of course root 
password must be change ....

73 de F5NLG



Le 05/08/2015 21:12, Aaron Crawford a écrit :
> Please see this forum thread:
> http://openrepeater.com/forums/topic/default-ssh-password-not-working
>
> I will take a look at your other post when I get a chance. Thanks.
>
>
> Aaron Crawford
> Allegheny Creative, LLC
> P.O. Box 681
> Falling Waters, WV 25419-0681
> 304-274-1800 phone
> www.AlleghenyCreative.com
>
>
> NOTICE: This communication is confidential and intended only for the 
> person or entity to which it is addressed and may be legally 
> privileged. If you are not the intended recipient, you are hereby 
> notified that you have received this message in error and that any 
> review, dissemination, distribution or copying of this message 
> including any attachments is strictly prohibited. Please notify the 
> sender by reply mail, and delete this communication from your system. 
> Failure to follow this process may be unlawful. Opinions, 
> Declarations, conclusions or any other information contained or 
> attached to this message that do not relate to the official business 
> of Allegheny Creative, LLC shall be understood as neither given nor 
> endorsed by it.
>
>
> > On Aug 5, 2015, at 2:05 PM, f5nlg <notifications@github.com> wrote:
> >
> > hello all , the ssh password doesn't work OpenRepeater ... and to 
> much complicated meaning A on French keyboard is Q why don't yu put 
> toor like password ... failtoban doesn't must not start at first boot 
> but have to select from control pannel ( my point of view ) , i search 
> to login in SSH for now ...
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenRepeater/OpenRepeater/issues/11#issuecomment-128113694>.
>

-- 
Jean-Philippe Piers
"7 rue du guic"
22810 Belle isle en terre
Tel: 02.36.56.78.79
Gsm: 06.71.78.37.93
