### ISSUE TITLE
Restart Script

### ISSUE THREAD

**Issue by abcrawford** [OpenRepeater/documents#13]
@rneese45,
I think we need to robustify the startup script. 

Options could be: start | stop | restart | status | web-status | info ....etc

START: would work as it does now, but should check to see if it is running first. 

RESTART: same, it should check if it run before it try's to stop, then stop, then may check to make sure it is stopped, then restart. 

WEB-STATUS: would be similar to status to check if it is run but return results that that can be read back into GUI. It could be as simple as 0 for stopped and 1 for runnning...but we may also be able to parse and pass back a php array that could contain other information like uptime, etc.

One thing to keep in mind, the way the restart is handled right now it disconnects itself from the process after it issues the command. So if it waits 10 secs to reload, then the dashboard will likely reload first and give a false status (giving we put the status on there).
Just some thoughts.

If it is having a bug and not cleaning up, the it may be we want to add line in to kill the process.

**Comment by RejectH0** [comment]
I have some Linux BASH programming experience.  I'm just starting to install the project onto a new RPi 3.  I just got my hands on all of the equipment that I needed (USB sound card, KF5INZ interface, etc.) and will begin to play around with it.

**Comment by alleghenycreative** [comment]
@RejectH0 we are working on that now. This thread is somewhat dated. But we have a helper shell script in place that we will be adding access to via various controls in the GUI.
