### ISSUE TITLE
Initial Hardware Design

### ISSUE THREAD

**Issue by alleghenycreative** [OpenRepeater/documents#5]
Design basic interface circuit and test with software

**Comment by f5nlg** [comment]
i have a shematic for interface in my svxlink pdf , here : https://www.dropbox.com/s/6ga8qpl2vlguiba/Install-de-svxlink-raspi2.pdf?dl=0  it's simple and works for 1 year now on F5ZIN repeater with 3 radio ports ( 50.540 , 145.400 and 430.400/439.800 )
